### ISSUE TITLE
Getting an AssertionError when tried to run 'test_fence.py'

### ISSUE THREAD

**Issue by DenisSergeevitch** [alex04072000/ObstructionRemoval#1]
Hi, I have changed `tfoptflow/model_base.py` with provided one, but when I am running a command `test_fence.py` I am getting an error:
`AssertionError: Do not use tf.reset_default_graph() to clear nested graphs. If you need a cleared graph, exit the nesting and create a new graph.`

Full log is here:
```
Traceback (most recent call last):
  File "test_fence.py", line 280, in <module>
    int(np.ceil(float(CROP_PATCH_W // (2 ** 3)) / 64.0)) * 64)
  File "test_fence.py", line 109, in PWC_full
    nn = ModelPWCNet(mode='test', options=nn_opts)
  File "tfoptflow/tfoptflow/model_pwcnet.py", line 226, in __init__
    super().__init__(name, mode, session, options)
  File "tfoptflow/tfoptflow/model_base.py", line 58, in __init__
    tf.reset_default_graph()
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 5852, in reset_default_graph
    raise AssertionError("Do not use tf.reset_default_graph() to clear "
```

**Comment by alex04072000** [comment]
Oops!
I updated a new version of `model_base.py`.
Please replace both `model_base.py` and `model_pwcnet.py` using the ones in my repo and try again.
If there are still other problems, please let me know.

**Comment by DenisSergeevitch** [comment]
Looks like it is fixed previous problem, but created a new one:
`ValueError: The passed save_path is not a valid checkpoint: tfoptflow/tfoptflow/models/pwcnet-lg-6-2-multisteps-chairsthingsmix/pwcnet.ckpt-595000`

I have shared my colab publicly, you can check it [here](https://colab.research.google.com/drive/1nPEnD1aa7NvsLHoW_GfwcZtREXEa_n8o), just press 'Run All" to get the same error.

Full log:
```
Traceback (most recent call last):
  File "test_fence.py", line 280, in <module>
    int(np.ceil(float(CROP_PATCH_W // (2 ** 3)) / 64.0)) * 64)
  File "test_fence.py", line 109, in PWC_full
    nn = ModelPWCNet(mode='test', options=nn_opts)
  File "tfoptflow/tfoptflow/model_pwcnet.py", line 226, in __init__
    super().__init__(name, mode, session, options)
  File "tfoptflow/tfoptflow/model_base.py", line 66, in __init__
    self.build_graph()
  File "tfoptflow/tfoptflow/model_base.py", line 267, in build_graph
    self.load_ckpt()
  File "tfoptflow/tfoptflow/model_base.py", line 187, in load_ckpt
    self.saver.restore(self.sess, self.last_ckpt)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 1282, in restore
    checkpoint_prefix)
```

**Comment by alex04072000** [comment]
The pre-trained weights for PWC-Net should be downloaded separately.
Please refer to their [repo](https://github.com/philferriere/tfoptflow/tree/master/tfoptflow) for more information.
We use the pre-trained model `pwcnet-lg-6-2-multisteps-chairsthingsmix/pwcnet.ckpt-595000`.

**Comment by DenisSergeevitch** [comment]
Oh, I see :) I have updated my colab, it is working now, thanks!

**Comment by Sicily-F** [comment]
Hi Denis,

I have tried using your Colabs and was wondering if you used it on your own images? I've been really struggling to get this repository to work locally, maybe you had a similar error?

(tensorflow1.1) C:\Users\Sicily\ObstructionRemoval>python test_fence.py
Traceback (most recent call last):
  File "test_fence.py", line 38, in <module>
    from model_pwcnet import ModelPWCNet, _DEFAULT_PWCNET_TEST_OPTIONS
  File "tfoptflow/tfoptflow\model_pwcnet.py", line 16, in <module>
    from ckpt_mgr import BestCheckpointSaver
  File "tfoptflow/tfoptflow\ckpt_mgr.py", line 55
    self._save_path = os.path.join(save_dir, f'{save_file}.ckpt')
                                                               ^
SyntaxError: invalid syntax

I also tried your  Colabs and was not able to get it to run or access the results!! Do you have another Colabs available? I'd love any pointers

**Comment by lyu-yx** [comment]
> Oh, I see :) I have updated my colab, it is working now, thanks!

Hi Denis & Alex
I met the similar problem with you when I trying to load the pwcNet parameters.

>INFO:tensorflow:Restoring parameters from tfoptflow/tfoptflow/models/pwcnet-lg-6-2-multisteps-chairsthingsmix/pwcnet.ckpt-595000
2021-04-19 12:19:21.313739: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Data loss: not an sstable (bad magic number)
Traceback (most recent call last):
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: not an sstable (bad magic number)
	 [[{{node save/RestoreV2}}]]


I have put all the four file from [link](https://drive.google.com/drive/folders/1gtGx_6MjUQC5lZpl6-Ia718Y_0pvcYou) under dir `tfoptflow/tfoptflow/models/pwcnet-lg-6-2-multisteps-chairsthingsmix/` but it fails. Can you help me out? Thanks a lot!
@DenisSergeevitch @alex04072000

**Comment by lyu-yx** [comment]
By the way, I tried Denis's colab link and modify a little bit. Can you help me to see why it is not work?[link](https://colab.research.google.com/drive/1p2rHYnTwWMtrf8gqfbFGWDyG3YBqgvpT#scrollTo=SMb4zFQt7zp8)
