### ISSUE TITLE
NotFoundError: ckpt_fence; No such file or directory

### ISSUE THREAD

**Issue by aekazitt** [alex04072000/ObstructionRemoval#8]
Here is my stacktrace

```
Traceback (most recent call last):
  File "test_fence.py", line 548, in <module>
    saver4.restore(sess, FLAGS.ckpt_path)
  File "/usr/local/anaconda3/envs/obstruction/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1276, in restore
    if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
  File "/usr/local/anaconda3/envs/obstruction/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/obstruction/lib/python3.7/site-packages/tensorflow/python/training/checkpoint_management.py", line 372, in checkpoint_exists
    if file_io.get_matching_files(pathname):
  File "/usr/local/anaconda3/envs/obstruction/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 363, in get_matching_files
    return get_matching_files_v2(filename)
  File "/usr/local/anaconda3/envs/obstruction/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 384, in get_matching_files_v2
    compat.as_bytes(pattern))
tensorflow.python.framework.errors_impl.NotFoundError: ckpt_fence; No such file or directory
```

The FLAGS.ckpt_path is defined in this Repo's `test_fence.py` at Line 24 as such:

```
tf.app.flags.DEFINE_string('ckpt_path', 'ckpt_fence/model.ckpt',
                           """If specified, restore this pretrained model """
```

I have installed TensorFlow (1.14.0) and other requirements the repo requested as followed:
* Clone `tfoptflow/tfoptflow` to project while overwriting `model_base.py` and `model_pwcnet.py`
* Download Pre-Trained PWC models to `tfoptflow/tfoptflow/models/` folder

The whole project is running on OSX so I choose tensorflow instead of tensorflow-gpu. Is there anything you recommend to fix this issue?

**Comment by laulampaul** [comment]
I face the same problem. Have you solve it?

**Comment by Sicily-F** [comment]
I had a similar issue, I have the same file structure, and am getting this error

(tensorflow1.1) C:\Users\Sicily\ObstructionRemoval>python test_fence.py
Traceback (most recent call last):
  File "test_fence.py", line 38, in <module>
    from model_pwcnet import ModelPWCNet, _DEFAULT_PWCNET_TEST_OPTIONS
  File "tfoptflow/tfoptflow\model_pwcnet.py", line 16, in <module>
    from ckpt_mgr import BestCheckpointSaver
  File "tfoptflow/tfoptflow\ckpt_mgr.py", line 55
    self._save_path = os.path.join(save_dir, f'{save_file}.ckpt')
                                                                                           ^
SyntaxError: invalid syntax

Does anyone have any clues? I'd be so grateful

**Comment by filipppp** [comment]
I believe that we just dont have the model provided, since I got the models from this colab: https://colab.research.google.com/drive/1kCG5SJd3usgzi6Bx979KiaO_YTanNVVz?usp=sharing and none of them worked as an input (changed the line in test_fence.py to different files)..

The author should just provide a working model on google drive and share it, instead of hosting it and then deleting it all the time.

**Comment by filipppp** [comment]
https://github.com/alex04072000/ObstructionRemoval/issues/7 I used the link he provided here, works now.
